setup2:
	mvn clean package
	./buildAndCopyToAWS.sh	2
setup3:
	mvn clean package
	./buildAndCopyToAWS.sh 3
setup5:
	mvn clean package
	./buildAndCopyToAWS.sh 5
setup8:
	mvn clean package
	./buildAndCopyToAWS.sh 8
setup9:
	mvn clean package
	./buildAndCopyToAWS.sh 9
